#!/usr/bin/env bash

if grep --version | grep -i bsd >/dev/null 2>&1; then
  grepprg='bsd'; grepver="$(grep --version | grep -m1 grep)"
elif grep --version | grep -i gnu >/dev/null 2>&1; then
  grepprg='gnu'; grepver="$(grep --version | grep -m1 grep)"
else
  echo 'Your version of grep is unknown (???)'
  exit 1
fi

argc="$#";: "$((i=0))"
while [ "$i" -lt "$argc" ]; do
  [ "$(echo "$1" | grep "'")" ] && sq='true'
  if [ "$1" = '--help' ] || [ "$1" = '-h' ] || [ "$1" = '--h' ]; then Help='true'
  elif [ "$1" = '--list' ] || [ "$1" = '--l' ];                  then List='true'
  elif [ "$1" = '--describe' ] || [ "$1" = '--desc' ];           then Describe='true'
  elif [ "$1" = '--raw' ];                                       then Raw='true'
  elif [ "$(echo "$1" | cut -c1-1)" = '-' ];                     then OPTS="$OPTS $1"
  elif [ "$1" = '::' ];                                          then exclude_active='true'
  elif [ "$OLD" = '' ] && [ "$NEW" = '' ]; then 
    if [ "$sq" ];
    then OLD="$(printf "\"%q\"" "$1")";
    else OLD="$(printf "'%q'" "$1")";
    fi
  elif [ "$OLD" ] && [ "$NEW" = '' ]; then 
    if [ "$sq" ];
    then NEW="$(printf "\"%q\"" "$1")";
    else NEW="$(printf "'%q'" "$1")";
    fi
  else
    isdir=''; [ "$(echo -n "$1" | tail -c1)" = '/' ] && isdir='true'
    if [ "$isdir" ]; then arg="$(echo "$1" | sed 's/.$//')"; else arg="$1"; fi
    if [ "$exclude_active" ]; then
      basearg="$(echo "$arg" | sed -ne 's!.*/\(.*\)$!\1!p')"
      if [ "$basearg" ] && [ "$grepprg" = 'gnu' ]; then
        if [ "$isdir" ];
        then printf "\n   WARNING: GNU grep --exclude doesn't support '$arg/', use '$basearg/' instead\n\n"
        else printf "\n   WARNING: GNU grep --exclude doesn't support '$arg', use '$basearg' instead\n\n"
        fi
        warning='true'
      fi
      if [ "$isdir" ]; then
        ED="$(echo $ED --exclude-dir=\'$arg\')" # don't use printf, don't want to escape wildcards in $arg
      else
        EF="$(echo $EF --exclude=\'$arg\')" # don't use printf, don't want to escape wildcards in $arg
      fi
    else
      if [ "$isdir" ]; then
        ID="$(printf "$ID '%q'" "$arg")"
      else
        IF="$(printf "$IF '%q'" "$arg")"
      fi
    fi
  fi
  shift;: "$((i=i+1))"
done
[ -z "$Raw" ] && ED="$ED --exclude-dir='.git'"
[ "$ID$IF" = '' ] && ID='.'

# [ "$Help" ] && echo "--help is active"
# [ "$List" ] && echo "--list is active"
# [ "$Describe" ] && echo "--describe is active"
# [ "$Raw" ] && echo "--raw is active"
# echo "OLD is $OLD"
# echo "NEW is $NEW"
# echo "ED is $ED"
# echo "EF is $EF"
# echo "ID is $ID"
# echo "IF is $IF"
# echo "OPTS are $OPTS"
# exit 0

if [ "$OLD" ] && [ "$NEW" ] && [ -z "$Help" ]; then
  if [ "$List" ]; then
    cmd="grep $OPTS -rEIl --color=always -e $OLD $ID $IF $ED $EF | less -RiMSFX#4"
  else
    cmd="grep $OPTS -rEIl -e $OLD $ID $IF $ED $EF --null | xargs -0 perl -pi -e 's!$(echo $OLD|xargs)!$(echo $NEW|xargs)!g'"
  fi;
  [ "$warning" ] && [ -z "$Describe" ] && read -p "Press Enter to continue"
  if [ "$Describe" ]; then
    echo "$cmd";
  else
    eval "$cmd";
    eval "grep $OPTS -rEIHnC3 --color=always -e $NEW $ID $IF $ED $EF | less -RiMSFX#4"
  fi
else
  echo "   Usage: rgrepf <old> <new> [INCLUDED...] [:: EXCLUDED...] [--OPTIONS...]"
  echo
  echo "   Search and replace <old> with <new> in [INCLUDED] files, ignoring [EXCLUDED] files."
  echo "   [INCLUDED] files are separated from [EXCLUDED] files by a '::'."
  echo "   By default, [INCLUDED] is the current directory."
  echo
  echo "   Examples:"
  echo "      rgrepf old new"
  echo "      rgrepf old new '*.py'"
  echo "      rgrepf old new file1.txt folder1/ :: folder1/file2.txt"
  echo "      rgrepf old new :: file1.txt '**/*.log'"
  echo
  echo "   Options(only for rgrepf):"
  echo "      --help       Show this help"
  echo "      --list       List the files that are affected"
  echo "      --describe   Show the full command that grepf transforms into"
  echo "      --raw        Raw unfiltered searches i.e. .git/ is filtered by default, this"
  echo "                   turns it off"
  echo
  echo "   Note:"
  echo "      Any [--OPTIONS] you can pass to grep, you can pass to grepf as well."
  echo "      If in doubt, wrap it in single quotes 'like this'"
  echo
  echo "   You are using: $grepver"
fi
